preset: symfony

linting: true

enabled:
  - header_comment
  - long_array_syntax
  - ordered_use
  - php_unit_construct
  - php_unit_strict
  - strict
  - strict_param

disabled:

finder:
  name:
    - "*.php"
